### PR TITLE
32: Use Argbash tool to generate macos-compatible opt parsing

### LINKED ISSUE #32: macOS compatibility
In the nautilus.sh script, the way the getops command is used is not compatible with macOS.
It would be great if the script could be made more portable (maybe by not using getops at all). 

Maybe an even better solution would be to have a multistage docker file where the first stage would generate the binary in an Ubuntu docker image and the second will run the generated jars.

### PR DESCRIPTION
**Pull request by ivanopagano**
Closes #32 

macos doesn't support some features of more recent versions of the `getopt` command.
This PR uses a code generation tool to create code that would parse the options without those advanced features.

The generation-tool information can be found [here](https://argbash.io)
It provides an online tool to generate the script without installing locally.

The currently generated script contains in the header comments, the macro script used to generate the options-parsing code, so that additional changes might be made re-using the tool.
The custom operational code instead, can be directly modified in the script.

### the code needs testing before approval
Locally the starting order didn't work when I tried to test the script, but I tried not to touch the original code that didn't have to do with command line parsing.

### CODE REVIEW

**Comment by bhaskarkishore** [comment]
Can you provide a specific example of what does not work on MacOS?

**Comment by ivanopagano** [comment]
> Can you provide a specific example of what does not work on MacOS?

If I get it correctly, `getopt` installed on macos doesn't support long options (e.g. --protocol, --tezos) so the script fails on execution

**Comment by ivanopagano** [comment]
I revisioned a bit the script to fix some argument handling and to make the startup order consistent.

I can still only make it work when starting conseil.

Running with --database gets me
```bash
Using build path: /Users/scalac/.nautilus
Configurations stored in /Users/scalac/Documents/projects/cryptonomics/Nautilus/docker/config/local
pgdata-local
Error response from daemon: No such container: postgres-local
Error: No such container: postgres-local
/Users/scalac/Documents/projects/cryptonomics/Nautilus/docker/app/postgres/build_postgres.sh: line 32: wget: command not found
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM postgres:10.3-alpine
 ---> 24a77bfbb9ee
Step 2/10 : ARG CONSEILDB_USER
 ---> Using cache
 ---> f98df031447c
Step 3/10 : ARG CONSEILDB_PASSWORD
 ---> Using cache
 ---> de305dab1717
Step 4/10 : ARG CONSEILDB_DBNAME
 ---> Using cache
 ---> 23121a1cf67a
Step 5/10 : ENV POSTGRES_USER=$CONSEILDB_USER
 ---> Using cache
 ---> eabd36de4740
Step 6/10 : ENV POSTGRES_PASSWORD=$CONSEILDB_PASSWORD
 ---> Using cache
 ---> 1f406fe0de6b
Step 7/10 : ENV POSTGRES_DB=$CONSEILDB_DBNAME
 ---> Using cache
 ---> 52c002826d2f
Step 8/10 : ENV POSTGRES_INITDB_ARGS="--nosync --lc-collate=C"
 ---> Using cache
 ---> 07d9ad861063
Step 9/10 : COPY ./conseil.sql /docker-entrypoint-initdb.d/conseil.sql
COPY failed: stat /var/lib/docker/tmp/docker-builder652237181/conseil.sql: no such file or directory
fatal: Unable to build postgres container
```
Which seems to have troubles finding the `conseil.sql` file anywhere, to generate the db schema.

While running with --tezos
```bash
Using build path: /Users/scalac/.nautilus
Configurations stored in /Users/scalac/Documents/projects/cryptonomics/Nautilus/docker/config/local
Error response from daemon: No such container: tezos-node-local
Error: No such container: tezos-node-local
sed: 1: "/Users/scalac/.nautilus ...": bad flag in substitute command: 'a'
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM tezos/tezos:protocol
manifest for tezos/tezos:protocol not found: manifest unknown: manifest unknown
fatal: Unable to build tezos container
```

might be getting some error because I choose a `build-path` containing a `.`?

**Comment by vishakh** [comment]
Stale

**Pull request closed without merging**
